"""
Resume file storage.

Files are written under a random key rather than their original filename. Two
reasons: a filename is attacker-controlled input and the obvious source of path
traversal, and a predictable path would let anyone who guesses it read someone
else's resume. Nothing here is served statically - every read goes through a
route that checks ownership first.
"""

from __future__ import annotations

import asyncio
import secrets
import shutil
from pathlib import Path

import config


def _root() -> Path:
    root = Path(config.STORAGE_DIR).resolve()
    root.mkdir(parents=True, exist_ok=True)
    return root


def _user_dir(user_id: int) -> Path:
    directory = _root() / f"user-{int(user_id)}"
    directory.mkdir(parents=True, exist_ok=True)
    return directory


def resolve(storage_key: str) -> Path:
    """
    Turn a stored key into an absolute path, refusing anything outside the root.

    Keys are generated by this module, so a key that escapes the storage root
    means either a bug or tampering; either way it must not resolve.
    """
    candidate = (_root() / storage_key).resolve()
    if not candidate.is_relative_to(_root()):
        raise ValueError(f"storage key escapes the storage root: {storage_key!r}")
    return candidate


async def save_resume(user_id: int, content: bytes, extension: str = ".pdf") -> str:
    """
    Write a resume and return its storage key.

    The extension comes from the detected format, not from the uploaded
    filename - a DOCX stored as .pdf downloads as a file nothing can open.
    """
    if extension not in {".pdf", ".docx"}:
        extension = ".pdf"
    directory = _user_dir(user_id)
    key = f"user-{int(user_id)}/{secrets.token_urlsafe(24)}{extension}"
    path = directory / Path(key).name

    def _write() -> None:
        path.write_bytes(content)

    await asyncio.to_thread(_write)
    return key


async def read_resume(storage_key: str) -> bytes | None:
    path = resolve(storage_key)

    def _read() -> bytes | None:
        if not path.is_file():
            return None
        return path.read_bytes()

    return await asyncio.to_thread(_read)


async def delete_resume(storage_key: str) -> None:
    try:
        path = resolve(storage_key)
    except ValueError:
        return

    def _delete() -> None:
        path.unlink(missing_ok=True)

    await asyncio.to_thread(_delete)


async def delete_user_files(user_id: int) -> None:
    """Remove everything belonging to one user. Called on account deletion."""
    directory = _root() / f"user-{int(user_id)}"

    def _delete() -> None:
        if directory.is_dir():
            shutil.rmtree(directory, ignore_errors=True)

    await asyncio.to_thread(_delete)
