"""tailored resume changes and scores

Revision ID: 692ac5d2ce23
Revises: 757944992c25
Create Date: 2026-09-14 22:16:08.899660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692ac5d2ce23'
down_revision: Union[str, Sequence[str], None] = '757944992c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default on every NOT NULL column, which autogenerate does not add.
    # Without it this migration fails the moment the table holds a single row:
    # SQLite cannot add a NOT NULL column whose default is NULL, and Alembic's
    # batch mode issues a plain ADD COLUMN rather than rebuilding the table.
    # The defaults are dropped afterwards so the application, not the database,
    # stays the one place deciding what a new row looks like.
    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('profile_version', sa.Integer(), nullable=False, server_default='1')
        )
        batch_op.add_column(
            sa.Column('tailored_profile', sa.JSON(), nullable=False, server_default='{}')
        )
        batch_op.add_column(
            sa.Column('changes', sa.JSON(), nullable=False, server_default='[]')
        )
        batch_op.add_column(
            sa.Column('accepted_ids', sa.JSON(), nullable=False, server_default='[]')
        )
        batch_op.add_column(
            sa.Column('rejected_changes', sa.JSON(), nullable=False, server_default='[]')
        )
        batch_op.add_column(sa.Column('before_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('after_score', sa.Integer(), nullable=True))

    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.alter_column('profile_version', server_default=None)
        batch_op.alter_column('tailored_profile', server_default=None)
        batch_op.alter_column('changes', server_default=None)
        batch_op.alter_column('accepted_ids', server_default=None)
        batch_op.alter_column('rejected_changes', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tailored_resumes', schema=None) as batch_op:
        batch_op.drop_column('after_score')
        batch_op.drop_column('before_score')
        batch_op.drop_column('rejected_changes')
        batch_op.drop_column('accepted_ids')
        batch_op.drop_column('changes')
        batch_op.drop_column('tailored_profile')
        batch_op.drop_column('profile_version')

    # ### end Alembic commands ###
