"""interview preps and cover letter claims

Revision ID: a514ed1c0d22
Revises: 692ac5d2ce23
Create Date: 2026-09-15 00:07:42.574107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a514ed1c0d22'
down_revision: Union[str, Sequence[str], None] = '692ac5d2ce23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_preps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'job_id', 'profile_version', name='uq_interview_cache_key')
    )
    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_preps_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_preps_profile_id'), ['profile_id'], unique=False)

    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        # server_default for the same reason as the previous migration: SQLite
        # cannot add a NOT NULL column whose default is NULL, so this would
        # fail against any database that already holds a cover letter.
        batch_op.add_column(
            sa.Column('unsupported_claims', sa.JSON(), nullable=False, server_default='[]')
        )

    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.alter_column('unsupported_claims', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_column('unsupported_claims')

    with op.batch_alter_table('interview_preps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_preps_profile_id'))
        batch_op.drop_index(batch_op.f('ix_interview_preps_job_id'))

    op.drop_table('interview_preps')
    # ### end Alembic commands ###
